name: handle PR comments
on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  actions: write

jobs:
  run_test:
    name: "Run e2e test"
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo github.event
      #     echo '${{ toJSON(github.event) }}'
      #     echo github
      #     echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v4
      - name: trigger e2e
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME=$(gh pr view --json headRefName --jq .headRefName ${{ github.event.issue.number }})
          echo "triggering e2e"
          gh workflow run --ref ${BRANCH_NAME} long-time-test-failure.yaml
          gh workflow run --ref ${BRANCH_NAME} long-time-test.yaml
