name: long time test
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To be able to set commit status
  statuses: write

jobs:
  commit-status-start:
    name: Commit status start
    runs-on: ubuntu-latest
    steps:
      - name: Set pending to commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ github.sha }}
      - name: display github context
        run: |
          echo github
          echo '${{ toJSON(github) }}'
  extract-github-ref:
    name: extract github.ref
    runs-on: ubuntu-latest
    outputs:
      github_ref: ${{ steps.extract.outputs.github_ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract github.ref
        id: extract
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # github.event_name = workflow_dispatch → pull/<pull_request_number>/merge
          # github.event_name push → github.ref
          if ${{ github.event_name == 'workflow_dispatch' }};then
            PR_number=$(gh pr view --json number -q .number)
            echo "github_ref=pull/${PR_number}/merge" >> $GITHUB_OUTPUT
          else
            echo "github_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          fi
  e2e:
    name: e2e
    needs:
    - commit-status-start # 実際にはe2eのstepの方が長くなるのは自明なのでいらないはず
    - extract-github-ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.extract-github-ref.outputs.github_ref }}
      - run: echo "this step very very long e2e test"
  e2e-hoge:
    name: e2e-hoge
    needs:
    - commit-status-start # 実際にはe2e-hogeのstepの方が長くなるのは自明なのでいらないはず
    - extract-github-ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.extract-github-ref.outputs.github_ref }}
      - run: |
          echo "this step very very long e2e-hoge test"
  commit-status-final:
    if: always()
    name: Commit Status Final
    needs:
      - e2e
      - e2e-hoge
    runs-on: ubuntu-latest
    steps:
      - name: Get final status
        id: final-status
        run: |
          if "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}"; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ github.sha }}
          status: ${{ steps.final-status.outputs.result }}
