name: long time test failure
on:
  workflow_dispatch:

permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To be able to set commit status
  statuses: write

jobs:
  commit-status-start:
    name: Commit status start
    runs-on: ubuntu-latest
    steps:
      - name: Set pending to commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ github.sha }}
  e2e:
    name: e2e
    needs: commit-status-start # 実際にはe2eのstepの方が長くなるのは自明なのでいらないはず
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this step very very long e2e test"
          false
  commit-status-final:
    if: always()
    name: Commit Status Final
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ github.sha }}
          status: ${{ needs.e2e.result }}
