name: long time test failure
on:
  workflow_dispatch:

permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To be able to set commit status
  statuses: write

jobs:
  commit-status-start:
    name: Commit status start
    runs-on: ubuntu-latest
    steps:
      - name: Set pending to commit status
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='pending' \
            -f target_url='${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
            -f description='pending' \
            -f context='${{ github.workflow }}'
  e2e:
    name: e2e
    needs: commit-status-start # 実際にはe2eのstepの方が長くなるのは自明なのでいらないはず
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "this step very very long e2e test"
          false
  e2e-hoge:
    name: e2e-hoge
    needs: commit-status-start # 実際にはe2e-hogeのstepの方が長くなるのは自明なのでいらないはず
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "this step very very long e2e-hoge test"
  commit-status-final:
    if: always()
    name: Commit Status Final
    needs:
      - e2e
      - e2e-hoge
    runs-on: ubuntu-latest
    steps:
      - name: Get final status
        id: final-status
        run: |
          if "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}"; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ github.sha }}
          status: ${{ steps.final-status.outputs.result }}
